logging:  # Logging configuration parameters
  level: DEBUG  # Level options: INFO|ERROR|DEBUG. Default: INFO
  output: console  # Output options: console|file. Default: console

aws:
  aws_key: xxxxxxxxxxxxxxxx
  aws_secret: xxxxxxxxxx
  sns_region: xxxxxxxxxxx
  sns_arn: xxxxxxxxx

pgsql:
  host: postgis
  user: urbo_admin
  password: urbo
  database: urbo
  port: 5432

carto:
  active: true
  api_key: XXXXXXXXXX
  user: XXXXX

watcherSchedule:
  - id_watcher: myidwatcher
    table: mytable
    schema: myschema
    column: TimeInstant
    update_freq: '*/30 * * * *'
    environment: carto|pgsql|both
    threshold:
      warning: 15
      error: 30
