logging:  # Logging configuration parameters
  level: DEBUG  # Level options: INFO|ERROR|DEBUG. Default: INFO
  output: console  # Output options: console|file. Default: console

aws:
  aws_key: xxxxxxxxxxxxxxxx
  aws_secret: xxxxxxxxxx
  sns_region: xxxxxxxxxxx
  sns_arn: xxxxxxxxx

pgsql:
  host: postgis
  user: urbo_admin
  password: urbo
  database: urbo
  port: 5432

carto:
  active: true
  api_key: XXXXXXXXXX
  user: XXXXX

notifications:
  subj_prefix: Urbo-Watcher-DEV

watcherSchedule:
  - id_watcher: dumps_wastecontainer
    table: dumps_wastecontainer_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '30 */30 * * * *'
    environment: both
    threshold:
      warning: 30
      error: 65
  - id_watcher: environment_weatherobserved
    table: environment_weatherobserved_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '15 */30 * * * *'
    environment: both
    threshold:
      warning: 25
      error: 50
  - id_watcher: environment_airqualityobserved
    table: environment_airqualityobserved_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '25 */30 * * * *'
    environment: both
    threshold:
      warning: 25
      error: 50
  - id_watcher: environment_noiseobserved
    table: environment_noiseobserved_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '35 */30 * * * *'
    environment: both
    threshold:
      warning: 25
      error: 50
  - id_watcher: waste_contenedores
    table: waste_contenedores_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '45 */30 * * * *'
    environment: both
    threshold:
      warning: 25
      error: 50
  - id_watcher: lighting_stcabinet
    table: lighting_stcabinet_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '55 */30 * * * *'
    environment: both
    threshold:
      warning: 25
      error: 50
  - id_watcher: parking_offstreetparking
    table: parking_offstreetparking_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '5 10 * * * *'
    environment: both
    threshold:
      warning: 20
      error: 80
  - id_watcher: parking_onstreetparking
    table: parking_offstreetparking_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '28 11 * * * *'
    environment: both
    threshold:
      warning: 20
      error: 80
  - id_watcher: parking_parkinggroup
    table: parking_parkinggroup_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '22 12 * * * *'
    environment: both
    threshold:
      warning: 20
      error: 80
  - id_watcher: parking_parkingspot
    table: parking_parkingspot_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '38 13 * * *'
    environment: both
    threshold:
      warning: 20
      error: 80
  - id_watcher: dumps_emptyings
    table: dumps_emptyings
    schema: distrito_telefonica
    column: dateemptying
    update_freq: '45 0 0,2,20,22 * * *'
    environment: both
    threshold:
      warning: 30
      error: 80
  - id_watcher: dumps_filling_agg
    table: dumps_fillingagg
    schema: distrito_telefonica
    column: day
    update_freq: '40 30 0 * * *'
    environment: carto
    threshold:
      warning: 1590
      error: 1600
  - id_watcher: environment_aqobserved_agg
    table: environment_aqobserved_measurand_agg
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '50 30 0 * * *'
    environment: carto
    threshold:
      warning: 1590
      error: 1600
  - id_watcher: parking_offstreetparking_agg_hour
    table: parking_offstreetparking_agg_hour
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '12 15 * * * *'
    environment: both
    threshold:
      warning: 80
      error: 150
  - id_watcher: parking_offstreetparking_agg_day
    table: parking_offstreetparking_agg_day
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '10 30 0 * * *'
    environment: both
    threshold:
      warning: 1590
      error: 1600
  - id_watcher: transport_trafficflowobserved
    table: transport_trafficflowobserved_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '19 */5 * * * *'
    environment: both
    threshold:
      warning: 10
      error: 40
  - id_watcher: transport_trafficflowobserved_agg_hour
    table: transport_trafficflowobserved_agg_hour
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '24 19 * * * *'
    environment: both
    threshold:
      warning: 150
      error: 200
  - id_watcher: transport_trafficflowobserved_agg_day
    table: transport_trafficflowobserved_agg_day
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '29 19 0 * * *'
    environment: both
    threshold:
      warning: 1590
      error: 1600
