logging:  # Logging configuration parameters
  level: DEBUG  # Level options: INFO|ERROR|DEBUG. Default: INFO
  output: console  # Output options: console|file. Default: console

aws:
  aws_key: xxxxxxxxxxxxxxxx
  aws_secret: xxxxxxxxxx
  sns_region: xxxxxxxxxxx
  sns_arn: xxxxxxxxx

pgsql:
  host: postgis
  user: urbo_admin
  password: urbo
  database: urbo
  port: 5432

carto:
  active: true
  api_key: XXXXXXXXXX
  user: XXXXX

notifications:
  subj_prefix: Urbo-Watcher-DEV

watcherSchedule:
  - id_watcher: dumps_wastecontainer
    table: dumps_wastecontainer_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '30 */30 * * * *'
    environment: both
    threshold:
      warning: 30
      error: 65
  - id_watcher: environment_weatherobserved
    table: environment_weatherobserved_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '15 */30 * * * *'
    environment: both
    threshold:
      warning: 25
      error: 50
  - id_watcher: environment_airqualityobserved
    table: environment_airqualityobserved_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '25 */30 * * * *'
    environment: both
    threshold:
      warning: 25
      error: 50
  - id_watcher: environment_noiseobserved
    table: environment_noiseobserved_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '35 */30 * * * *'
    environment: both
    threshold:
      warning: 25
      error: 50
  - id_watcher: waste_contenedores
    table: waste_contenedores_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '45 */30 * * * *'
    environment: both
    threshold:
      warning: 25
      error: 50
  - id_watcher: lighting_stcabinet
    table: lighting_stcabinet_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '55 */30 * * * *'
    environment: both
    threshold:
      warning: 25
      error: 50
  - id_watcher: parking_offstreetparking
    table: parking_offstreetparking_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '5 10 * * * *'
    environment: both
    threshold:
      warning: 20
      error: 80
  - id_watcher: parking_onstreetparking
    table: parking_offstreetparking_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '28 11 * * * *'
    environment: both
    threshold:
      warning: 20
      error: 80
  - id_watcher: parking_parkinggroup
    table: parking_parkinggroup_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '22 12 * * * *'
    environment: both
    threshold:
      warning: 20
      error: 80
  - id_watcher: parking_parkingspot
    table: parking_parkingspot_lastdata
    schema: distrito_telefonica
    column: TimeInstant
    update_freq: '38 13 * * *'
    environment: both
    threshold:
      warning: 20
      error: 80
