FROM node:6.14-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
COPY package.json /usr/src/app/

RUN \
    set -x \
    && apk add --no-cache bash \
    && npm install \
    && npm cache clean --force

COPY . .

EXPOSE 3000

CMD [ "npm", "start" ]
