version: "3"

services:
  watcher:
    build:
      context: .
      dockerfile: Dockerfile.new
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "3005:3000"
      - "9229:9229"
    command: npm run-script start-dev
    network_mode: bridge
    restart: unless-stopped

  # https://hub.docker.com/r/dockage/mailcatcher/
  # ref internally here: wget https://raw.githubusercontent.com/dockage/mailcatcher/master/docker-compose.yml
  mailcatcher:
    restart: always
    image: dockage/mailcatcher:0.6.5
    ports:
    - "1080:1080"
    - "1025:1025"    
    

volumes:
  node_modules: