version: "3"

services:
  watcher:
    build:
      context: .
      dockerfile: Dockerfile.new
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "3005:3000"
      - "9229:9229"
    command: npm run-script start-dev
    network_mode: bridge
    restart: unless-stopped

volumes:
  node_modules:
