version: "3"

services:
  watcher:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "9229:9229"
    network_mode: bridge
    command: npm run-script start-dev
    restart: unless-stopped

volumes:
  node_modules: